# Generated by Django 2.0.7 on 2018-07-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('royal', models.PositiveIntegerField(default=0)),
                ('full_house', models.PositiveIntegerField(default=0)),
                ('straight', models.PositiveIntegerField(default=0)),
                ('eye_less', models.PositiveIntegerField(default=0)),
                ('oracle', models.PositiveIntegerField(default=0)),
                ('nostradamus', models.PositiveIntegerField(default=0)),
                ('trelawney', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'summaries',
                'db_table': 'psh_summary',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'psh_topic',
            },
        ),
    ]
